name: Get Armbian Kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_armbian_file:
        description: "armbian_file http url"
        required: true
        default: ""
  #schedule:
    #- cron: "0 17 * * 0"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV

      - name: Download armbian img
        id: down
        run: |
          wget ${{ github.event.inputs.set_armbian_file }}

      - name: get Armbian Kernel
        id: getkernel
        run: |
          #https://github.com/a520ass/Armbian-build/releases/download/Armbian_Aml_TVBOX_GF_MESON64_V22_11.24.1948/Armbian_22.11.0_Aml-s9xx-box_jammy_edge_6.0.9.img.gz
          httpurl=${{ github.event.inputs.set_armbian_file }}
          file=${httpurl##*/}
          gzip -d ${file}
          # 替换文件名
          img=${file/img.gz/img}
          loopname=`sudo losetup -P -f --show ${img}`
          mountname=${loopname//dev/mnt}
          sudo mkdir -p ${mountname}
          sudo mkdir -p ${mountname}/boot

          sudo mount ${loopname}p2 ${mountname}
          sudo mount ${loopname}p1 ${mountname}/boot

          echo "${mountname}/boot"

          cd ${mountname}
          tar -czf /workdir/boot.tar.gz boot
          cd ${mountname}/usr/lib/modules
          tar -czf /workdir/modules.tar.gz *
          echo "::set-output name=status::success"

      - name: Upload file to Release
        uses: ncipollo/release-action@main
        if: steps.getkernel.outputs.status == 'success' && !cancelled()
        with:
          tag: Armbian_Kernel_${{ env.COMPILE_STARTINGTIME }}
          artifacts: /workdir/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian kernel image
